name: dctkit
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh
  - hyperfine
  - jax==0.5.0
  - jaxopt
  - numpy
  - pygmo
  - python
  - python-gmsh
  - scipy
  - typeguard
  - yaml
  - jupyterlab
  - trame
  - ipywidgets
  - pyvista
  - pip
  - petsc
  - petsc4py
  - pip:
    - pygmsh
    - tox-conda
    